// This file is auto-generated by @hey-api/openapi-ts

import {
  createClient,
  createConfig,
  type Options,
} from "@hey-api/client-axios";
import type { GetUsersData, GetUsersResponse } from "./types.gen";

export const client = createClient(createConfig());

/**
 * Returns a list of users.
 * Optional extended description in CommonMark or HTML.
 */
export const getUsers = <ThrowOnError extends boolean = false>(
  options?: Options<GetUsersData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetUsersResponse,
    unknown,
    ThrowOnError
  >({
    ...options,
    url: "/users",
  });
};
